### ISSUE TITLE
Build Failure: Error while running OPI from version 0.4.1 or main

### ISSUE THREAD

**Issue by tcrst** [bestinslot-xyz/OPI#46]
Hellom I'm encountering an issue while trying to run OPI from version 0.4.1 or the main branch. The problem arises during the build process when attempting to build ord. Specifically, I'm receiving the following error:

`cd ord; cargo build --release;  returns on 0.4.1 and main branches`

```
   Compiling time v0.3.31
error[E0282]: type annotations needed for `Box<_>`
  --> /root/.cargo/registry/src/index.crates.io-6f17d22bba15001f/time-0.3.31/src/format_description/parse/mod.rs:83:9
   |
83 |     let items = format_items
   |         ^^^^^
...
86 |     Ok(items.into())
   |              ---- type must be known at this point
   |
help: consider giving `items` an explicit type, where the placeholders `_` are specified
   |
83 |     let items: Box<_> = format_items
   |              ++++++++

For more information about this error, try `rustc --explain E0282`.
```

**Comment by layer1g** [comment]
Seems like an issue with the `time` package, try this for now:

```cargo update -p time```

It builds with `time v0.3.36`.

**Comment by tcrst** [comment]
Thanks, it fixed the build.
